### ISSUE TITLE
Some UTF8 multibyte chars are splitted into invalid UTF8 sequences

### ISSUE THREAD

**Issue by gfx** [increments/greenmat#2]
```ruby
p Greenmat::Markdown.new(
    Greenmat::Render::HTML.new,
    fenced_code_blocks: true
  ).render("```ム")
```

produces:

```ruby
"<pre><code class=\"\xE3\x83\"></code></pre>\n"
```

which must be `"<pre><code class=\"ム\"></code></pre>\n"`. Because `\xE3\x83` is a invalid UTF8 sequence, the output result easily causes encoding errors (e.g. by Nokogiri).

Note: redcarpet also has the same bug.

**Comment by gfx** [comment]
There is a PR in redcarpet: https://github.com/vmg/redcarpet/pull/464

**Comment by r7kamura** [comment]
@gfx We'll check it and move to solve this problem. Thank you for your reporting 👍
